name: Staging Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::755199214013:role/jackpot-staging-cicd-role
          aws-region: us-east-2

      - name: Deploy Web
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=i-08219b6e485f830bb" \
            --comment "Staging deploy (web)" \
            --parameters 'commands=["sudo -u ubuntu /var/www/jackpot/deploy/deploy.sh"]'

      - name: Deploy Worker
        run: |
          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --targets "Key=instanceids,Values=i-05eb319ceb5bf1851" \
            --comment "Staging deploy (worker)" \
            --parameters 'commands=["sudo -u ubuntu /var/www/jackpot/deploy/deploy.sh"]'
